### ISSUE TITLE
DirectedEdge : lack of documentation

### ISSUE THREAD

**Issue by KenAlin** [Darkyler/graphJava#2]
Hi there,
The constructor for DirectedEdge may be lacking some documentation.
It took a table of Vertex as input, let's say [Vertex a, Vertex b]. How are they linked ? a->b or b->a ?

Regards

**Comment by BenAfonso** [comment]
Was pretty sure it was on the doc ! 

In the case you've specified, [Vertex a, Vertex b], The vertex is directed from A to B (a->b).
You can try it by creating a DirectedEdge object then trying to call the getSource() and getDestination() methods. Check doc if you need informations.
